/**
 * Worker Sales Service Layer
 * Service functions to calculate sales generated by a worker
 */

import { getDailySales, SalesFilters } from '@/lib/services/graphql/queries';

export interface WorkerSalesSummary {
  totalRevenue: number;
  totalTransactions: number;
  averageTicketValue: number;
  totalItems: number;
}

/**
 * Calculate sales generated by a worker
 * @param workerName - Worker's name (matches waiter_name in sales records)
 * @param startDate - Start date (YYYY-MM-DD)
 * @param endDate - End date (YYYY-MM-DD)
 * @returns Sales summary
 */
export async function fetchWorkerSales(
  workerName: string,
  startDate: string,
  endDate: string
): Promise<WorkerSalesSummary> {
  const summary: WorkerSalesSummary = {
    totalRevenue: 0,
    totalTransactions: 0,
    averageTicketValue: 0,
    totalItems: 0,
  };

  try {
    // Fetch all sales records for this worker
    const filters: SalesFilters = {
      waiterName: workerName,
    };

    // Fetch all pages to get complete data
    let page = 1;
    let hasMore = true;
    const allRecords: any[] = [];
    const uniqueTickets = new Set<string>();

    while (hasMore) {
      const result = await getDailySales(
        startDate,
        endDate,
        page,
        100, // Fetch 100 records per page
        filters
      );

      if (result.success && result.records) {
        allRecords.push(...result.records);
        
        // Track unique transactions (ticket_key)
        result.records.forEach((record) => {
          if (record.ticket_key) {
            uniqueTickets.add(record.ticket_key);
          }
        });

        // Check if there are more pages
        hasMore = page < (result.totalPages || 1);
        page++;
      } else {
        hasMore = false;
      }
    }

    // Calculate totals
    summary.totalRevenue = allRecords.reduce((sum, record) => {
      const revenue = record.total_inc_vat 
        ? Number(record.total_inc_vat) 
        : (record.unit_price && record.quantity 
          ? Number(record.unit_price) * Number(record.quantity) 
          : 0);
      return sum + revenue;
    }, 0);

    summary.totalItems = allRecords.reduce((sum, record) => {
      return sum + Math.abs(Number(record.quantity) || 0);
    }, 0);

    summary.totalTransactions = uniqueTickets.size;
    summary.averageTicketValue = summary.totalTransactions > 0
      ? summary.totalRevenue / summary.totalTransactions
      : 0;
  } catch (error) {
    console.error('[Worker Sales Service] Error fetching sales:', error);
  }

  return summary;
}


